### ISSUE TITLE
[FEATURE] Start Advanced Flow with Text-tag

### ISSUE THREAD

**Issue by murderbeard** [mennovanhout/flutter-hdashboards-issues#57]
There seems to be no support for starting advanced flows with text-tags. In my case I use an advanced flow that starts with a text-tag which sets up volume, channels, smart apps, et cetera on my home theatre set-up with values like: TV, PS4, SWITCH, YOUTUBE.

Advanced flows with a normal (parameterless) start do show up in the drop down when adding cards to the dashboard. This means I can also add a parameterless start to the previously mentioned flow which will add it to the dropdown, but obviously I cannot select which start node to trigger.

~Cheers

**Comment by mennovanhout** [comment]
Hey would you expect to set this value on adding the flow or on press when you start the flow?

**Comment by murderbeard** [comment]
Hi. Would expect, when adding a card/button to the dashboard, you can type in the value of you want to 'send' to the flow's start trigger. Similar to how you can trigger it in homey's own 'start flow with text' card. 

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/23704547/af1f7b3c-afb8-40e2-bd0d-325ed8a37c2e)

Just realized there are also similar cards but with: number, yes/no and image as the parameter type. But personally I only ever use the string version.

![image](https://github.com/mennovanhout/flutter-hdashboards-issues/assets/23704547/289cdadd-6fb1-4f71-ad0b-9d7952110494)

**Comment by mennovanhout** [comment]
I understand your frustration, and I would like to add this in the future. However for the upcoming period I think we have way more important stuff since there is a workaround available:

- make flow that starts another flow with given input.

Because indeed there should also be support for: booleans, numbers etc.

I'm sorry and Im stilling willing to re-open this issue in the future.
